version: '2'

services:

  builder:
    build: './builder'
    volumes:
      - './tests/:/scripts/'
      - '/var/run/docker.sock:/var/run/docker.sock'
    working_dir: '/scripts'

  meta-cpp:
    extends: builder
    command: [
      'python',
      'meta-cpp.py',
      '$PWD/srcs/meta-cpp/',
      '$PWD/lib/meta-cpp/'
    ]
